/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: Enlight5.JPG
* Dimensions:  128 * 62
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR acBruinRacing[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXX_, ___XXXXX, _______X, XXXX__XX, XXX_XXXX, XXXX____, ___XXXXX, ______XX, XXX____X, XXXX____, ________,
  ________, ____XXXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXX_, ___XXXXX, _______X, XXXX__XX, XXX_XXXX, XXXXX___, ___XXXXX, ______XX, XXX____X, XXXX____, ________,
  ________, ____XXXX, XXXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX, ___XXXXX, _______X, XXXX__XX, XXX_XXXX, XXXXXX__, ___XXXXX, ______XX, XXX____X, XXXX____, ________,
  ________, ____XXXX, X_______, XXXXX__X, XXXXXXXX, XXXXXXXX, ___XXXXX, _______X, XXXX__XX, XXX_XXXX, XXXXXXX_, ___XXXXX, __XXXX__, ___XXXX_, ________, ________,
  ________, ____XXXX, ________, XXXXX__X, XXXX____, ___XXXXX, ___XXXXX, _______X, XXXX__XX, XXX_XXXX, XXXXXXXX, ___XXXXX, __XXXX__, ___XXXX_, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXX___X, XXXX____, ___XXXXX, ___XXXXX, _______X, XXXX__XX, XXX_XXXX, X_XXXXXX, X__XXXXX, __XXXX__, ___XXXX_, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXXX, ___XXXXX, _______X, XXXX__XX, XXX_XXXX, X__XXXXX, X__XXXXX, __XXXX__, ___XXXX_, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXXX__X, XXXX_XXX, XXXXXXX_, ___XXXXX, _______X, XXXX__XX, XXX_XXXX, X___XXXX, XX_XXXXX, ______XX, XXX____X, XXXX____, ________,
  ________, ____XXXX, X_______, XXXXX__X, XXXX__XX, XXXXXX__, ___XXXXX, _______X, XXXX__XX, XXX_XXXX, X___XXXX, XXXXXXXX, ______XX, XXX____X, XXXX____, ________,
  ________, ____XXXX, ________, XXXXX__X, XXXX___X, XXXXX___, ___XXXXX, XXXXXXXX, XXXX__XX, XXX_XXXX, X____XXX, XXXXXXXX, ______XX, XXX____X, XXXX____, ________,
  ________, ____XXXX, XXXXXXXX, XXXXX__X, XXXX____, XXXXXX__, ___XXXXX, XXXXXXXX, XXXX__XX, XXX_XXXX, X_____XX, XXXXXXXX, __XXXX__, ___XXXX_, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXXX__X, XXXX____, __XXXXX_, ___XXXXX, XXXXXXXX, XXXX__XX, XXX_XXXX, X______X, XXXXXXXX, __XXXX__, ___XXXX_, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXXX__X, XXXX____, ___XXXXX, ____XXXX, XXXXXXXX, XXX___XX, XXX_XXXX, X_______, XXXXXXXX, __XXXX__, ___XXXX_, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXX____X, XXXX____, ____XXXX, X____XXX, XXXXXXXX, XX____XX, XXX_XXXX, X_______, _XXXXXXX, __XXXX__, ___XXXX_, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXX_____, ______XX, XXXXX___, _____XXX, XXXXXXXX, XXXX__XX, XXX_XXXX, XXXXX___, ___XXXXX, ___XXXXX, XXXXXXXX, XXXX____, ________,
  ________, ____XXXX, XXXXXXXX, XXXX____, _____XXX, XXXXX___, ____XXXX, XXXXXXXX, XXXX__XX, XXX_XXXX, XXXXX___, ___XXXXX, __XXXXXX, XXXXXXXX, XXXX____, ________,
  ________, ____XXXX, XXXXXXXX, XXXXX___, _____XXX, XXXXXX__, ____XXXX, XXXXXXXX, XXXX__XX, XXX_XXXX, XXXXXX__, ___XXXXX, __XXXXXX, XXXXXXXX, XXXX____, ________,
  ________, ____XXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXX__, ___XXXXX, XXXXXXXX, XXXX__XX, XXX_XXXX, XXXXXXX_, ___XXXXX, __XXXXXX, XXXXXXXX, XXXX____, ________,
  ________, ____XXXX, X_______, XXXXX___, ____XXXX, XXXXXXX_, ___XXXXX, ________, ______XX, XXX_XXXX, XXXXXXXX, ___XXXXX, __XXXX__, ________, ________, ________,
  ________, ____XXXX, X______X, XXXXX___, ___XXXXX, __XXXXX_, ___XXXXX, ________, ______XX, XXX_XXXX, X_XXXXXX, X__XXXXX, __XXXX__, _XXXXXXX, XXXX____, ________,
  ________, ____XXXX, XXXXXXXX, XXXX____, __XXXXXX, ___XXXXX, ___XXXXX, ________, ______XX, XXX_XXXX, X__XXXXX, XX_XXXXX, __XXXX__, ____XXXX, XXXX____, ________,
  ________, ____XXXX, X_XXXXXX, XXXX____, __XXXXX_, ___XXXXX, X__XXXXX, ________, ______XX, XXX_XXXX, X___XXXX, XX_XXXXX, __XXXX__, ______XX, XXXX____, ________,
  ________, ____XXXX, X__XXXXX, XX______, _XXXXXX_, XXXXXXXX, X__XXXXX, ________, ______XX, XXX_XXXX, X____XXX, XXXXXXXX, __XXXX__, _______X, XXXX____, ________,
  ________, ____XXXX, X___XXXX, XX______, _XXXXX__, XXXXXXXX, XX_XXXXX, ________, ______XX, XXX_XXXX, X____XXX, XXXXXXXX, __XXXXX_, _______X, XXXX____, ________,
  ________, ____XXXX, X____XXX, XXX_____, XXXXXX_X, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXX__XX, XXX_XXXX, X_____XX, XXXXXXXX, __XXXXXX, XXXXXXXX, XXXX____, ________,
  ________, ____XXXX, X_____XX, XXXX____, XXXXX___, _____XXX, XXX_XXXX, XXXXXXXX, XXXX__XX, XXX_XXXX, X______X, XXXXXXXX, __XXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ____XXXX, X_______, XXXXX__X, XXXXX___, ______XX, XXX__XXX, XXXXXXXX, XXXX__XX, XXX_XXXX, X_______, XXXXXXXX, ___XXXXX, XXXXXXXX, XXX_____, ________,
  ________, ____XXXX, X_______, _XXXXX_X, XXXX____, ______XX, XXXX___X, XXXXXXXX, XXXX__XX, XXX_XXXX, X_______, _XXXXXXX, _____XXX, XXXXXXXX, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX

};

GUI_Bitmap_t bmBruinRacing = {
  128, /* XSize */
  62, /* YSize */
  16, /* BytesPerLine */
  1, /* BitsPerPixel */
  acBruinRacing,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */

